server:
  port: 8082

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    import: nacos:file-service-space, nacos:rabbit-config
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.96.132:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.96.132:8848
        file-extension: yaml
        username: nacos
        password: nacos
      server-addr: 192.168.96.132:8848
    openfeign:
      circuitbreaker: # 熔断器配置
        enabled: true
      httpclient:
        enabled: true
        max-connections: 1000 # 最大连接数
        connection-timeout: 3000 # 连接超时时间
        ok-http:
          read-timeout: 3000 # 读超时时间
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.96.132:8848
      application: seata-server
      username: nacos
      password: nacos
      group: DEFAULT_GROUP
#      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 192.168.96.132:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace:
      data-id: seata-server.properties
  tx-service-group: default_tx_group
  service:
#    vgroup-mapping:
#      default_tx_group: default
#    vgroupMapping:
#      default_tx_group: default


temp:
  file:
    path: "D:\\zhawu\\temp\\"