server:
  port: 8084

spring:
  application:
    name: space-service
  config:
    import: nacos:space-service-space, nacos:seata-config, nacos:rabbit-config, optional:nacos:zipkin-config
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: nacos
      config:
        server-addr: nacos:8848
        file-extension: yaml
        username: nacos
        password: nacos
      server-addr: nacos:8848