spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: nacos
      config:
        server-addr: nacos:8848
        username: nacos
        password: nacos
        encode: UTF-8
        file-extension: yml
  config:
    import:
      - optional:nacos:gateway-service-space
      - optional:nacos:zipkin-config
server:
  port: 10086