spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.96.132:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.96.132:8848
        username: nacos
        password: nacos
        encode: UTF-8
        file-extension: yml
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 100
            redis-rate-limiter.requestedTokens: 1
  config:
    import:
      - optional:nacos:gateway-service-space
server:
  port: 10086

logging:
  level:
    org.springframework.cloud.gateway: DEBUG