server:
  port: 8085
spring:
  application:
    name: note-service
  config:
    import: nacos:note-service-space, nacos:rabbit-config
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: nacos
      config:
        server-addr: nacos:8848
        file-extension: yaml
        username: nacos
        password: nacos
      server-addr: nacos:8848

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    web: debug