server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: nacos
      config:
        server-addr: nacos:8848
        username: nacos
        password: nacos
        encode: UTF-8
        file-extension: yml
        refresh-enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
      httpclient:
        enabled: true
  config:
    import:
      - optional:nacos:user-service-space
      - optional:nacos:rabbit-config
      - optional:nacos:zipkin-config