#spring:
#  cloud:
#    openfeign:
#      circuitbreaker: # 熔断器配置
#        enabled: true
#      httpclient:
#        enabled: true
#        max-connections: 1000 # 最大连接数
#        connection-timeout: 3000 # 连接超时时间
#        ok-http:
#          read-timeout: 3000 # 读超时时间